spring.application.name=jwt-auth

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/jwtdb
spring.datasource.username=root
spring.datasource.password=

#Auto create tables
spring.jpa.hibernate.ddl-auto=update
#Show queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
